#日志配置，此处使用默认日志
logging:
 config: classpath:config/logback.xml

spring:
 resources:
  static-locations: static/
 thymeleaf:
  prefix: templates/

server:
 port: 8088
 servlet:
  context-path: /jees-webs