#日志配置，此处使用默认日志
logging:
  config: classpath:config/logback.xml

spring:
 application:
  name: WebApplication
 autoconfigure:
  exclude:org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
 config:
  location: config/
 resources:
  static-locations: static/
 mvc:
  static-path-pattern: /**
 devtools:
  restart:
   enabled: false
 thymeleaf:
  cache: false
  prefix: classpath:/templates/
  check-template-location: true
  suffix: .html
  encoding: UTF-8
  content-type: text/html
  mode: HTML
# Redis数据库索引（默认为0）
 redis:
  database: 0
  host: 192.168.3.128
  port: 6379
  password: root
  pool:
# 连接池最大连接数（使用负值表示没有限制）
   max-active: -1
# 连接池最大阻塞等待时间（使用负值表示没有限制）max-wait
   max-wait: -1
# 连接池中的最大空闲连接
   max-idle: 10
# 连接池中的最小空闲连接
   min-idle: 0
# 连接超时时间（毫秒）
   timeout: 3000
  package: com.jees.game.entity

server:
 port: 8080

jees:
 webs:
  install:
   file: classpath:.install
   tpl: install
   step: 4
  dwr:
   debug: true
   url: /dwr
  maxSession: 1000
  superman: superman
  superpwd: 6
  encodePwd: true
  defPage: index
  templates: default
  login: login
  logout: logout
  identity: 10000
  default:
   assets: assets
   access: true
 jdbs:
  enable: false